server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Pay
          destination: forthcafe
          contentType: application/json
        event-out:
          destination: forthcafe
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082

# delivery service 호출 주소
api:
  url:
    delivery: http://localhost:8083

# message service 호출 주소
api:
  url:
    message: http://localhost:8085

# circuit breaker 설정 start
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    # 전역설정
    default:
      #execution.isolation.thread.timeoutInMilliseconds: 610
      execution.isolation.thread.timeoutInMilliseconds: 30000
# circuit breaker 설정 end            
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Pay
          destination: forthcafe
          contentType: application/json
        event-out:
          destination: forthcafe
          contentType: application/json

# delivery service 호출 주소
api:
  url:
    delivery: http://Delivery:8080

# message service 호출 주소
api:
  url:
    message: http://Message:8085

# circuit breaker 설정 start
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    # 전역설정
    default:
      #execution.isolation.thread.timeoutInMilliseconds: 610
      execution.isolation.thread.timeoutInMilliseconds: 30000
# circuit breaker 설정 end
  