apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: Message
          image: skuser02.azurecr.io/message:v1
          ports:
            - containerPort: 8080
          # autoscale start
          resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
          # autoscale end
          ### config map start
          #env:
          #  - name: SYS_MODE
          #    valueFrom:
          #      configMapKeyRef:
          #        name: systemmode
          #        key: sysmode
          ### config map end                                    
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5